# Generated by Django 2.1.2 on 2021-01-20 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heyurl', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
